[keyboard]
; The values are the dos key codes for the respective keys
UP = 72
DOWN = 80
LEFT = 75
RIGHT = 77
JUMP = 56
ACTION = 29

[joystick]
; 0 is the first joystick button, 3 is the fourth joystick button
JUMP = 0
ACTION = 1

[sound]
ENABLE_SOUND = true
ENABLE_MUSIC = true