title: DosPloatformGame
description: >- # this means to ignore newlines until "baseurl:"
  DosPlatformGame is a retro platform game that runs on real DOS hardware.
  Using Dosbox it runs on all modern platforms as well.

# Build settings
theme: minima


