title: DosPloatformGame
description: >- # this means to ignore newlines until "baseurl:"
  DosPlatformGame is a retro platform game that runs on real DOS hardware.
  Using Dosbox it runs on all modern platforms as well.

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


